version: '3'

services:
  web:
    restart: always
    build: ./rates
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: 
      - .env

  postgres:
    restart: always
    build: ./db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata:
